import "bootstrap/dist/css/bootstrap.min.css"
import "./styles/globals/variables.scss";
export const metadata = {
  title: "PixelBoard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
